### ISSUE TITLE
non dotnet core projects

### ISSUE THREAD

**Issue by Drewster727** [CycloneDX/cyclonedx-dotnet#1]
Does this support scanning of .net framework projects?
I'm unable to get this to work for my .net framework 4.5/4.6 solutions.

**Comment by stevespringett** [comment]
It works for any .NET project that uses Visual Studio project or solutions and uses NuGet.

**Comment by Drewster727** [comment]
I seem to get this when scanning any of my solutions:
![image](https://user-images.githubusercontent.com/4528753/51337873-eb0fdc80-1a4d-11e9-91d7-ee4129378638.png)

Let me know -- I can provide snippets of the sln file.

**Comment by stevespringett** [comment]
Interesting. If you can provide a solution (with projects) that can reproduce this behavior and do so without disclosing confidential information, I'd like to take a look. I'd need to be able to recreate it.

Perhaps you could send the sln and csproj's with confidential info redacted and without any sources.

steve.springett@owasp.org

**Comment by Drewster727** [comment]
@stevespringett I just sent you a zip of a test solution that reproduces the issue. It was a relatively large zip b/c I included the packages folder. Let me know if you did not receive it.

Thanks!

**Comment by stevespringett** [comment]
@Drewster727 Did not receive.

**Comment by Drewster727** [comment]
@stevespringett just sent you an email with a download link. Sorry about that!

**Comment by stevespringett** [comment]
Received. Will investigate.

**Comment by stevespringett** [comment]
I was able to get past the error only to discover the projects are using manually managed dependencies instead of Nuget. Nuget is actually a requirement as the CycloneDX utility will reach out to NuGet to retrieve additional info not present in PackageReference defined in a project. I need to specifically state this in the readme as I think that's an oversight on my end.

The projects I've seen in the attachment do not have a PackageReference, they simply have a Reference. This would normally not be an issue. A Reference can very easily be parsed as it contains the name and version of a component. But for some mysterious reason, the versions of all the components (except for Moq) do not match the versions in NuGet. You may want to ask Microsoft why this is but it appears if x.x.x.0 is used in a Reference, then the last .0 is dropped to conform to semantic versioning. But if a non .0 value is used, then it keeps it.

Take FluentAssertions as an example. In the project it's defined as 4.14.0.0, whereas NuGet defines it as 4.14.0

At this point, I'm able to generate a BOM from the project you supplied, but it still has some issues. Will try to sort it out later tonight or tomorrow.

**Comment by stevespringett** [comment]
So it appears that NuGet is actually being used, but in the older packages.config format. The versions in this file match what is in NuGet.

So instead of parsing the unmanaged Reference in the project, I'm going to add support for packages.config.

So the end result should be able to create a BOM from managed dependencies (via NuGet) from solutions (sln), projects (csproj, vsproj), and packages.config.

**Comment by Drewster727** [comment]
Support for packages.config world be fantastic. One other thing to note about that test project I sent you... I removed references from the packages.config file to some of our in-house packages that get pulled from our internally hosted nuget server. Is that going to cause any problems? How will those items get looked up? Do you support querying internal nuget servers for package info?

Thanks again!

**Comment by stevespringett** [comment]
Creating a BOM from a solution or individual projects requires that NuGet dependencies are included in the projects. In your case they are not.

The tool will now accept the location to an individual packages.config file and will create a BOM from that in the same way that specifying an individual project will.

Because packages.config are decoupled from projects and there could be multiple packages.config for a given solution, the tool will now accept a directory instead of a file. If a directory is specified, then the dependencies defined in all decoupled files (packages.config) will be included in the BOM. This is likely what you'll want.

An additional parameter (url) was included to specify an alternative repo url. It expects the repo to be v3-flatcontainer compatible.

The executable name has changed from `CycloneDX` to `dotnet CycloneDX`. This was a necessary change so that conflicts with other CycloneDX ecosystem tools do not occur.

Version 0.3.0 has been published to NuGet.

**Comment by Drewster727** [comment]
@stevespringett  One more question on this subject -- I see that you added the additional url parameter, however, what if we have a mix of packages from our own/internal nuget server, and several from nuget.org? That is a common scenario.

**Comment by stevespringett** [comment]
Resolution depends on how the external NuGet repo is configured. In the Java/Maven world, a single internal repo can be configured to only host internally managed artifacts, act as a 'golden repo' for all 'blessed' external artifacts, or provide resolution to an external repo. So if I want to resolve an internal artifact from an internal repo, but my project also has external artifacts, specifying only the internal repo URL is all that's required. Hopefully NuGet works the same way. I have no way to reproduce or test this behaviour so if it doesn't do this, I may likely need a PR that's been tested in this type of environment.

BOMs are a statement of fact. Uploading multiple BOMs to a single project in Dependency-Track will not merge them. However, the CycloneDX NPM module has the capability or merging multiple BOMs when a BOM is created. So first, create a BOM from your non-NPM project, then create a BOM from the NPM project and specify the first BOM that you want to merge in. This will create a single BOM that can be uploaded to DT.

If you're in a scenario where there are dozens of BOMs that need to be merged, there are plenty of open-source tools that will merge XML files together. The CycloneDX schema was intentionally designed rather simplistically to account for this.

**Comment by Drewster727** [comment]
@stevespringett I was able to utilize 0.3.0 and successfully generated a bom file!

However, uploading to DT the UI shows it uploaded and is processing it, but the dependencies never appear. I see in the logs of DT that it saw it as an unsupported format:
![image](https://user-images.githubusercontent.com/4528753/51551906-1bcc8900-1e35-11e9-8595-fabb73a2ea7c.png)

Not sure if cyclonedx-dotnet is generated malformed xml? I'm sending you the xml via email.

Thanks!

**Comment by stevespringett** [comment]
Received the BOM, it validates successfully, but for some reason .NET doesn't save an XML file as UTF-8 even if the XML declaration states UTF-8.  Googling reveals that other folks are having the same issue and they have to do some rather bizarre workarounds to get it to save properly. I would have thought this would have worked properly out-of-the-box, but it doesn't.

Quick workaround would be to open the file and resave as UTF-8, but I'll work on fixing the issue and pushing a new version (hopefully later today).

**Comment by stevespringett** [comment]
0.3.1 has been published to NuGet which resolves the UTF-8 issue. It will be available shortly.

**Comment by rajesh2887** [comment]
can help on below issue.unable to genearte bom using jenkins pipeline.
commands executed and succeed : dotnet tool install --global CycloneDX --version 1.0.0

error while execute :             bat 'dotnet CycloneDX myproject.sln -o /output/bom'

2020-07-22 13:37:09 Retrieving GitHub license for repository angular-ui/bootstrap and ref master
2020-07-22 13:37:31 
2020-07-22 13:37:31 Unhandled Exception: System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2020-07-22 13:37:31    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2020-07-22 13:37:31    --- End of inner exception stack trace ---
2020-07-22 13:37:31    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2020-07-22 13:37:31    at System.Threading.Tasks.ValueTask`1.get_Result()
2020-07-22 13:37:31    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2020-07-22 13:37:31    at System.Threading.Tasks.ValueTask`1.get_Result()
2020-07-22 13:37:31    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
2020-07-22 13:37:31    at System.Threading.Tasks.ValueTask`1.get_Result()
2020-07-22 13:37:31    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2020-07-22 13:37:31    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2020-07-22 13:37:31    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2020-07-22 13:37:31    at CycloneDX.Services.GithubService.GetGithubLicenseAsync(String githubLicenseUrl) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/GithubService.cs:line 160
2020-07-22 13:37:31    at CycloneDX.Services.GithubService.GetLicenseAsync(String licenseUrl) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/GithubService.cs:line 129
2020-07-22 13:37:31    at CycloneDX.Services.NugetService.GetComponentAsync(String name, String version, String scope) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/NugetService.cs:line 172
2020-07-22 13:37:31    at CycloneDX.Services.NugetService.GetComponentAsync(NugetPackage package) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/NugetService.cs:line 210
2020-07-22 13:37:31    at CycloneDX.Program.OnExecuteAsync() in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 205
2020-07-22 13:37:31    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
2020-07-22 13:37:31    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
2020-07-22 13:37:31    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
2020-07-22 13:37:31 --- End of stack trace from previous location where exception was thrown ---
2020-07-22 13:37:31    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
2020-07-22 13:37:31    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
2020-07-22 13:37:31    at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 84
2020-07-22 13:37:31    at CycloneDX.Program.<Main>(String[] args)
[Pipeline] }

**Comment by coderpatros** [comment]
@rajesh2887 I'm assuming your build server is locked down for open internet access. If that's the case the `--disable-github-licenses` option should resolve this.

But it would be better to open a new issue instead of commenting on an unrelated issue that was closed over a year ago.
