### ISSUE TITLE
Unhandled exception when nuget.org is not available.

### ISSUE THREAD

**Issue by zerovoid0** [CycloneDX/cyclonedx-dotnet#182]
I am trying to run CycloneDX on a build server that does not have internet access.  My packages are hosted in a package source on the LAN that the build server does have access to.  CycloneDX gets an error like this while trying to retrieve information for one of the libraries in my solution.  Since its my own library, it does not have a NuGet package.  CycloneDX can't find a local package file, so it tries to connect to nuget.org which it cannot.  I think that CycloneDX should be able to run without access to the internet.

         Retrieving System.Threading.Tasks.Extensions 4.0.0
         Retrieving System.Threading.Thread 4.0.0
         Retrieving System.Threading.ThreadPool 4.0.10
         Retrieving System.Xml.ReaderWriter 4.0.11
         Retrieving System.Xml.XDocument 4.0.11
         Retrieving System.Xml.XmlDocument 4.0.1
         Retrieving System.Xml.XmlSerializer 4.0.11
         Retrieving System.Xml.XPath 4.0.1
         Retrieving System.Xml.XPath.XmlDocument 4.0.1
         Retrieving My.Library 1.0.0-176678
         
         Unhandled Exception: System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
            at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
            --- End of inner exception stack trace ---
            at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
            at System.Threading.Tasks.ValueTask`1.get_Result()
            at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            at System.Threading.Tasks.ValueTask`1.get_Result()
            at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
            at System.Threading.Tasks.ValueTask`1.get_Result()
            at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
            at CycloneDX.Extensions.HttpClientExtensions.GetXmlStreamAsync(HttpClient httpClient, String url) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Extensions/HttpClientExtensions.cs:line 37
            at CycloneDX.Services.NugetService.GetComponentAsync(String name, String version) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/NugetService.cs:line 107
            at CycloneDX.Services.NugetService.GetComponentAsync(NugetPackage package) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/NugetService.cs:line 209
            at CycloneDX.Program.OnExecuteAsync() in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 179
            at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
            at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
            at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
            at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
            at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 69
            at CycloneDX.Program.<Main>(String[] args)

This is the part of the code that is making the network request that fails.  I think it should either catch the network exception, or else give the user the option to remove nuget.org as a package source to avoid this request.

            if (nuspecFilename == null)
            {
                var url = _baseUrl + name + "/" + version + "/" + name + ".nuspec";
                using (var xmlStream = await _httpClient.GetXmlStreamAsync(url).ConfigureAwait(false))
                {
                    if (xmlStream != null) nuspecReader = new NuspecReader(xmlStream);
                }
            }
            else
            {
                using (var xmlStream = _fileSystem.File.Open(nuspecFilename, System.IO.FileMode.Open, System.IO.FileAccess.Read))
                {
                    nuspecReader = new NuspecReader(xmlStream);
                }
            }

**Comment by coderpatros** [comment]
Hi @zerovoid0, that error message isn't pretty, I'll need to do something about that.

Does specifying your local package repository using the `--url` option fix this?

I do need to do some work in this space. The tool should automatically use any configured package sources for this type of thing.

**Comment by coderpatros** [comment]
@zerovoid0 is this a local project reference? I've just merged #189 which should fix this if that is the case.

**Comment by zerovoid0** [comment]
Thanks for your quick response.  Yes, it is a local project reference.  I retested with the latest version and it got further but hit another error.  It looks like there is a license lookup step that also assumes internet connectivity will be available.  For my own purposes I ended up just commenting out some of these internet dependent checks and running that modified version on my build server for now.

Retrieving GitHub license for repository AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet and ref master
         Unhandled exception. System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
          ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
            at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
            --- End of inner exception stack trace ---
            at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
            at CycloneDX.Services.GithubService.GetGithubLicenseAsync(String githubLicenseUrl)
            at CycloneDX.Services.GithubService.GetLicenseAsync(String licenseUrl)
            at CycloneDX.Services.NugetService.GetComponentAsync(String name, String version, String scope)
            at CycloneDX.Services.NugetService.GetComponentAsync(NugetPackage package)
            at CycloneDX.Program.OnExecuteAsync()
            at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
            at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
            at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
            at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
            at CycloneDX.Program.Main(String[] args)
            at CycloneDX.Program.<Main>(String[] args)

**Comment by coderpatros** [comment]
@zerovoid0 that's another error that should probably be reported in a much nicer way :)

Try passing the `--disable-github-licenses` parameter. It was included for this exact use case.

I did think about adding handling for this to continue generating the BOM. But came to the conclusion that it was better to cancel on errors like this because otherwise you could end up with an incomplete BOM.

**Comment by zerovoid0** [comment]
OK, I tried with `--disable-github-licenses` and it worked great!
