### ISSUE TITLE
Build server error

### ISSUE THREAD

**Issue by Drewster727** [CycloneDX/cyclonedx-dotnet#2]
Running the latest cyclonedx-dotnet (0.3.1) on my TFS build server.
Notice the /Users/steve/... path?
Did a development version get installed? If so, how can I rectify this?

```2019-01-23T15:30:33.5463613Z dotnet cyclonedx . -o .\bom\dotnet 
2019-01-23T15:30:34.4838674Z » Analyzing: F:\Agents\Agent01\_work\4\s\Audio\APITestHarnes\packages.config
2019-01-23T15:30:34.4838674Z   Getting packages                                              
2019-01-23T15:30:40.6871154Z ##[error]Unhandled Exception: System.IO.IOException: The handle is invalid
2019-01-23T15:30:40.6871154Z ##[error]   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
2019-01-23T15:30:40.6871154Z ##[error]   at CycloneDX.Program.AnalyzeProjectAsync(String projectFile) in /Users/steve/Development/CycloneDX/cyclonedx-dotnet/CycloneDX/Program.cs:line 177
2019-01-23T15:30:40.6871154Z ##[error]   at CycloneDX.Program.AnalyzeDirectoryAsync(String projectPath) in /Users/steve/Development/CycloneDX/cyclonedx-dotnet/CycloneDX/Program.cs:line 157
2019-01-23T15:30:40.6871154Z ##[error]   at CycloneDX.Program.OnExecute() in /Users/steve/Development/CycloneDX/cyclonedx-dotnet/CycloneDX/Program.cs:line 79
2019-01-23T15:30:40.6871154Z ##[error]   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
2019-01-23T15:30:40.6871154Z ##[error]   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
2019-01-23T15:30:40.6871154Z ##[error]   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
2019-01-23T15:30:40.6871154Z ##[error]--- End of stack trace from previous location where exception was thrown ---
2019-01-23T15:30:40.6871154Z ##[error]   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
2019-01-23T15:30:40.6871154Z ##[error]   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
2019-01-23T15:30:40.7027422Z ##[error]   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 97
2019-01-23T15:30:40.7027422Z ##[error]   at CycloneDX.Program.Main(String[] args) in /Users/steve/Development/CycloneDX/cyclonedx-dotnet/CycloneDX/Program.cs:line 45```

**Comment by Drewster727** [comment]
Interestingly, when I login as the build service user on the build server, and run the command directly, it works...
![image](https://user-images.githubusercontent.com/4528753/51618611-39acf300-1ef4-11e9-97da-2befadb83e74.png)

**Comment by stevespringett** [comment]
0.3.2 published. Will be available shortly.

**Comment by Drewster727** [comment]
Hmm, so I uninstalled 0.3.1 and installed 0.3.2 -- seems to still happen:
![image](https://user-images.githubusercontent.com/4528753/51620727-9b6f5c00-1ef8-11e9-81cb-af87d2a571d6.png)

Any tips?

**Comment by stevespringett** [comment]
The path issue seems to be expected behavior. Someone at Microsoft must think that information disclosure in error messages is a good thing.

Regarding execution. I only have the ability to execute from command line. I don't have access to a Windows machine so cannot powershell. It appears to be caught on line 177 which is:

```csharp
Console.SetCursorPosition(Console.CursorLeft, Console.CursorTop - 1);
```

Perhaps powershell is doing something weird with the console. Don't know.

**Comment by Drewster727** [comment]
I also just tried loading cyclonedx-dotnet into the local working directory:
![image](https://user-images.githubusercontent.com/4528753/51622441-387fc400-1efc-11e9-9f70-6acd064d0917.png)

@stevespringett note that I can run this via powershell on a windows machine outside of the build operation without problems. (same script I'm running in the build)

**Comment by Drewster727** [comment]
OK, another update... I got around the problem by totally silencing any output from the tool:
```Start-Process -WindowStyle Hidden -Wait -FilePath "dotnet-cyclonedx.exe" -ArgumentList $bomArgs | Out-Null```

**Comment by stevespringett** [comment]
Thanks for the stackoverflow link. I removed the setting of cursor. There were two occurrances of this in the code which have since been removed. I pushed 0.3.3 to NuGet and it should be available shortly.

If you could test this and verify that it works without the workaround, that would be great.

Thanks for your patience and help in getting the dotnet plugin to where it needs to be.

**Comment by Drewster727** [comment]
@stevespringett  confirmed! 0.3.3 resolved the issue. Thank you!
