### ISSUE TITLE
NullReferenceException if no dependencies are present

### ISSUE THREAD

**Issue by Eckii24** [CycloneDX/cyclonedx-dotnet#436]
With MR #435 you introduced dependency graphs. If the processed project has no dependencies the following code snippet will lead to a `NullReferenceException` if `package.Dependencies` is null:

See [here](https://github.com/CycloneDX/cyclonedx-dotnet/pull/435/files?authenticity_token=file-filters%5B%5D=.cs#diff-24d2e82a9d79ceb3c5a78da46d1d0a6a1a4ac40f010f01e20660062c6935636cR266)
```c#
             foreach (var package in packages)
                {
                    var packageDepencies = new Dependency
                    {
                        Ref = bomRefLookup[package.Name],
                        Dependencies = new List<Dependency>()
                    };
                    foreach (var dep in package.Dependencies)
                    {
                        transitiveDepencies.Add(bomRefLookup[dep]);
                        packageDepencies.Dependencies.Add(new Dependency
                        {
                            Ref = bomRefLookup[dep]
                        });
                    }
                    dependencies.Add(packageDepencies);
                }
```

error message:
```
» Analyzing: /builds/[...].vbproj
  Attempting to restore packages
File not found: "/builds/[...]/obj/project.assets.json", "/builds/[...].vbproj" 
  No packages found
  Found packages.config. Will attempt to process
[...]
Retrieving Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.8
Retrieving Microsoft.CodeAnalysis.VersionCheckAnalyzer 2.9.8
Retrieving Microsoft.CodeQuality.Analyzers 2.9.8
[...]
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CycloneDX.Program.OnExecuteAsync() in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 268
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 109
   at CycloneDX.Program.<Main>(String[] args)
Aborted (core dumped)
```

**Comment by alexfowler09** [comment]
I dont if is the same situation

I have a problem with newest version of CycloneDx where the users made a typo with packageName in csproj file
Swashbuckle.AspNetCore.SwaggerUi

And the name of the package is
Swashbuckle.AspNetCore.SwaggerUI

And because of that a exception had been throw in Program.cs, line 275

I discovered the typo issue because i cloned the CycloneDx project and changed the code to set everywhere with .ToUpper()

I dont know if it should be changed, but Im comenting in case that someone has the same situation
