### ISSUE TITLE
Unable to run the tool in the 2.1.2 version (1 of 12 pipelines failed)

### ISSUE THREAD

**Issue by patspaeth** [CycloneDX/cyclonedx-dotnet#442]
After updating the cyclonedx-dotnet tool to V2.1.2 (from v1.6.4) in 1 of 12 pipeline it failed because of:
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'xxx.xxx.xxx.xxx' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CycloneDX.Program.OnExecuteAsync()
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 110
   at CycloneDX.Program.<Main>(String[] args)
```

I have executed cyclonedx with following parameters:
``` 
dotnet dotnet-CycloneDX --exclude-test-projects --exclude-dev -o SBOM -biop D:\a\1\s/artifacts -imp cycloneDX-metadata.xml PM.BE.sln
```
Maybe it has something similar to #437

**Comment by AnFa1978** [comment]
Problem is a cyclical dependency with NuGet package

**Comment by patspaeth** [comment]
Closed because issue was solved by removing a cyclic dependency of nuget packages
