### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object with LinkLibraryDependencies

### ISSUE THREAD

**Issue by jovmilan95** [CycloneDX/cyclonedx-dotnet#463]
I get error System.NullReferenceException: Object reference not set to an instance of an object, in vcsxproj files where this projectReference is present.
`    <ProjectReference>
      <LinkLibraryDependencies>true</LinkLibraryDependencies>
    </ProjectReference>`
    
 Error
 
 ```
  Getting project references
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CycloneDX.Services.ProjectFileService.GetProjectReferencesAsync(String projectFilePath) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/ProjectFileService.cs:line 189
   at CycloneDX.Services.ProjectFileService.RecursivelyGetProjectReferencesAsync(String projectFilePath) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/ProjectFileService.cs:line 226
   at CycloneDX.Services.SolutionFileService.GetSolutionProjectReferencesAsync(String solutionFilePath) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX.Core/Services/SolutionFileService.cs:line 70
   at CycloneDX.Services.SolutionFileService.GetSolutionNugetPackages(String solutionFilePath, String baseIntermediateOutputPath, Boolean excludeTestProjects) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX
.Core/Services/SolutionFileService.cs:line 96
   at CycloneDX.Program.OnExecuteAsync() in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 183
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 97
   at CycloneDX.Program.<Main>(String[] args)
```

**Comment by mtsfoni** [comment]
The reported issue was fixed by #565 (should be included in version >= 2.5.1)

If there is another constellation that causing an exception with vcsxproj please open a new issue and provide additional information.
