### ISSUE TITLE
KeyNotFoundException throws when create Bom

### ISSUE THREAD

**Issue by lwyxxj** [CycloneDX/cyclonedx-dotnet#512]
I got error KeyNotFoundException, I am using cyclone-dotnet 2.3.0

Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'airc.loggingsdk.common' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CycloneDX.Program.OnExecuteAsync()
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 113
   at CycloneDX.Program.<Main>(String[] args)

**Comment by killi199** [comment]
I have the same Problem. But I only have it on the current master, the Version 2.3.0 works fine for me. The error only occurs when there is a Subdependency that is also included in the Project. For example:
NuGet1 (Version 1.0) has NuGet2 (Version 1.0) as Subdependency. But the Project includes NuGet2 in Version 1.1. Then it crashes for me.
