### ISSUE TITLE
KeyNotFoundException with version interval

### ISSUE THREAD

**Issue by sduquette-devolutions** [CycloneDX/cyclonedx-dotnet#518]
Test version: github master branch

I am getting a KeyNotFoundException. The error happens at the following line, `dep` is `'(awssdk.core, [3.7.8.9, 4.0.0))` but `bomRefLookup` contains `("awssdk.core", "3.7.8.9")`. This might be related to #512. I will try to make reproduction project I can share.

```csharp
transitiveDepencies.Add(bomRefLookup[(dep.Key.ToLower(CultureInfo.InvariantCulture), dep.Value.ToLower(CultureInfo.InvariantCulture))]);
```
https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/CycloneDX/Program.cs#L286

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '(awssdk.core, [3.7.8.9, 4.0.0))' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CycloneDX.Program.OnExecuteAsync() in C:\dev\External\cyclonedx\cyclonedx-dotnet\CycloneDX\Program.cs:line 286
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in C:\dev\External\cyclonedx\cyclonedx-dotnet\CycloneDX\Program.cs:line 116
   at CycloneDX.Program.<Main>(String[] args)
```

**Comment by sduquette-devolutions** [comment]
I was able to create a project that reproduces the error https://github.com/sduquette-devolutions/CyclonedxDotnetRepro.

The dependency for AWSSDK.Core appears as an interval on [nuget.org](https://www.nuget.org/packages/AWSSDK.S3/3.7.8.15). AWSSDK.Core is a ProjectReference of AWSSDK.S3 (see [code](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/AWSSDK.S3.NetStandard.csproj#L59)).
![image](https://user-images.githubusercontent.com/70600710/161821577-a652162b-c1ff-4d84-8584-7c7300a177bc.png)

**Comment by rilehudd** [comment]
I also ran into this problem as well. 
I created a [PR ](https://github.com/CycloneDX/cyclonedx-dotnet/pull/516) that looks at the resolved version.

I like the simplicity of your change, but I'm not sure it will return the actual dependency which is realized on package restoration.

**Comment by sduquette-devolutions** [comment]
Yes, the "patch" on our fork was just to work around the issue for now and is probably wrong.
