### ISSUE TITLE
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly

### ISSUE THREAD

**Issue by verzada** [CycloneDX/cyclonedx-dotnet#522]
Is there a way to set the api key for a nuget repo or better yet; use the nuget.config defined in the user profile?

dotnet cyclonedx seems to default to nuget.org, our build agent cannot access it.
If we point to our internal repo, we'll get a 500 error due to our repoes requires an api key.

Is there a way to solve this hurdle?

**Comment by verzada** [comment]
Actually. We found out the issue.

Swashbuckle 5.6.0 for .net framework references WebActivatorEx, which depends on Microsoft.Web.Infrastructure 1.0.0 which causes cyclonedx to go to api.nuget.org

https://www.nuget.org/packages/Swashbuckle/

**Comment by verzada** [comment]
More information about the exception:
When the exception occurs, cyclonedx does not continue to the next package:

```
Unhandled exception. System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (api.nuget.org:443)
[15:08:39]	 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[15:08:39]	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[15:08:39]	   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[15:08:39]	   --- End of inner exception stack trace ---
[15:08:39]	   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
[15:08:39]	   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[15:08:39]	   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[15:08:39]	   at CycloneDX.Extensions.HttpClientExtensions.GetStreamWithStatusCheckAsync(HttpClient httpClient, String url) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Extensions/HttpClientExtensions.cs:line 39
[15:08:39]	   at CycloneDX.Services.NugetService.GetComponentAsync(String name, String version, Nullable`1 scope) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/NugetService.cs:line 128
[15:08:39]	   at CycloneDX.Services.NugetService.GetComponentAsync(NugetPackage package) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/NugetService.cs:line 300
[15:08:39]	   at CycloneDX.Program.OnExecuteAsync() in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 261
[15:08:39]	   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
[15:08:39]	   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
[15:08:39]	   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
[15:08:39]	--- End of stack trace from previous location ---
[15:08:39]	   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
[15:08:39]	   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
[15:08:39]	   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 113
[15:08:39]	   at CycloneDX.Program.<Main>(String[] args)
```
