### ISSUE TITLE
Null reference exception when project file has a project reference to an unsupported project

### ISSUE THREAD

**Issue by LapNik** [CycloneDX/cyclonedx-dotnet#582]
I have a .csproj project file that has a project reference to a .vcxproj project. Trying to generate a bom for this solution causes a null reference exception:
```
» Analyzing: C:\path\CppProject.vcxproj
  Getting project references
Getting project references
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CycloneDX.Services.ProjectFileService.GetProjectReferencesAsync(String projectFilePath) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectFileService.cs:line 205
   at CycloneDX.Services.ProjectFileService.RecursivelyGetProjectReferencesAsync(String projectFilePath) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectFileService.cs:line 242
   at CycloneDX.Services.SolutionFileService.GetSolutionProjectReferencesAsync(String solutionFilePath) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/SolutionFileService.cs:line 72
   at CycloneDX.Services.SolutionFileService.GetSolutionNugetPackages(String solutionFilePath, String baseIntermediateOutputPath, Boolean excludeTestProjects) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/SolutionFileService.cs:line 98
   at CycloneDX.Program.OnExecuteAsync() in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 212
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 113
   at CycloneDX.Program.<Main>(String[] args)
```
`SolutionFileService` already filters its own projects according to file extension. It should probably also filter the recursively retrieved project references. I'm not sure if there should be some alert logged about not being able to parse the complete project graph.

**Comment by mtsfoni** [comment]
This seems to be the same as #463 and should this be as well fixed by #565.

If not, I'd appreciate a new issue with some more detailed information of the xml-node in the vcxproj causing the exception.
