### ISSUE TITLE
2.4.1 regression: `--url` ignored, `api.nuget.org` used instead

### ISSUE THREAD

**Issue by nil4** [CycloneDX/cyclonedx-dotnet#597]
After upgrading cyclonedx-dotnet to v2.4.1, a regression was observed. 

When operating in an environment with restricted internet access where `api.nuget.org` is not accessible, earlier versions would use the value specified by `--url` as an alternative NuGet feed URL. For instance, with cyclonedx-dotnet v2.3.0, a command line like below would work as expected:

```cmd
dotnet.exe cyclonedx -ns -dgl --url https://on-premises.url/repository/nuget-v3/index.json App.sln
```

After upgrading to cyclonedx-dotnet v2.4.1, and keeping the same command line arguments, the tool fails at runtime while attempting to connect to `api.nuget.org`. The stack trace is:

```
Unhandled exception. NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json.
 ---> System.Net.Http.HttpRequestException: No such host is known. (api.nuget.org:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at NuGet.Protocol.ServerWarningLogHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSourceAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass5_1.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Protocol.TimeoutUtility.StartWithTimeout[T](Func`2 getTask, TimeSpan timeout, String timeoutMessage, CancellationToken token)
   at NuGet.Protocol.HttpRetryHandler.SendAsync(HttpRetryHandlerRequest request, String source, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Boolean isRetry, Boolean isLastAttempt, Guid sessionId, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResourceProvider.TryCreate(SourceRepository sourceRepository, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
   at CycloneDX.Services.NugetV3Service.GetComponentAsync(String name, String version, Nullable`1 scope) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/NugetV3Service.cs:line 152
   at CycloneDX.Services.NugetV3Service.GetComponentAsync(NugetPackage nugetPackage) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/NugetV3Service.cs:line 320
   at CycloneDX.Program.OnExecuteAsync(CommandLineApplication app) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 281
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 130
   at CycloneDX.Program.<Main>(String[] args)
```

The reason appears to be that in `NugetInputModel.cs`, the method `Create` ignores the `baseUrl` input parameter (corresponding to the `--url` command-line argument) completely, _unless explicit credentials (user name / password) are also specified_:

https://github.com/CycloneDX/cyclonedx-dotnet/blob/bce08814da755e4db4efe6afcb45bdab0d4c0a56/CycloneDX/Models/NugetInputModel.cs#L22-L35

In our setup, authentication credentials are not necessary to retrieve NuGet package information from the on-premises system. It is unexpected that the `--url` command-line argument is ignored silently in this case.

Can the current behavior be reviewed and, ideally, restored to work the same way that previous versions did?

**Comment by jonahbohlmann** [comment]
Hello,

in the latest version, I have the same problem.

--url seems to have no effect. I only get information, that my package could not be found on nuget.org.

Any idea?

```
docker run --mount type=bind,source="$(pwd)",dst=/app \
     cyclonedx/cyclonedx-dotnet -r \
     --out /app/out.sbom
     --url https://<reg>/artifactory/api/nuget/<feed>/index.json \
     /app/app.sln
```

Output:
```
Found the following local nuget package cache locations:
    /root/.nuget/packages/

» Solution: /app/app.sln
  Getting projects

» Analyzing: /app/src/app.csproj
  Getting project references
  No project references found
  1 project(s) found


» Analyzing: /app/src/app.csproj
  Attempting to restore packages
Dotnet restore failed:
  Determining projects to restore...
/app/src/app.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json
/app/src/app.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json
/app/src/app.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json
  Failed to restore /app/src/app.csproj (in 2.18 min).

```

Thanks!
