### ISSUE TITLE
Did anyone figure out solution for using version 2.7.0 ? I am facing this issue if I run it in Linux VM in azure pipelines as well as local machine but it is working without any issues in my local windows machine, not sure what causing the issue. I also tried to run in windows VMs in azure pipelines, still causing same issue, not sure how it is working locally with windows machine. Did anyone face the similar issue ?

### ISSUE THREAD

**Issue by gkrishna240988** [CycloneDX/cyclonedx-dotnet#664]
Did anyone figure out solution for using version 2.7.0 ? I am facing this issue if I run it in Linux VM in azure pipelines as well as local machine but it is working without any issues in my local windows machine, not sure what causing the issue. I also tried to run in windows VMs in azure pipelines, still causing same issue, not sure how it is working locally with windows machine. Did anyone face the similar issue ?
**Unhandled exception. System.IO.InvalidDataException: Central Directory corrupt.
 ---> System.IO.IOException: An attempt was made to move the position before the beginning of the stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---**

_Originally posted by @gkrishna240988 in https://github.com/CycloneDX/cyclonedx-dotnet/issues/603#issuecomment-1457574110_

**Comment by Bertk** [comment]
similar issue #692 692

**Comment by GeorgRottensteiner** [comment]
Running into the same issue, found no workarounds yet.
The scanned solution has a .NET 4.8, asp.net project, test project, DbUp project and a few WCF services.

Running with this command from PowerShell running inside a Team City Windows agent:
./tools/dotnet-CycloneDX --exclude-dev --exclude-test-projects --recursive --out ./bom $file.FullName


`07:26:30    ---> System.IO.IOException: An attempt was made to move the position before the beginning of the stream.
07:26:30      at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
07:26:30      at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
07:26:30      --- End of inner exception stack trace ---
07:26:30      at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
07:26:30      at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
07:26:30      at CycloneDX.Services.NugetV3Service.GetNuspec(String name, String version, String nuspecFilename, FindPackageByIdResource resource)
07:26:30      at CycloneDX.Services.NugetV3Service.GetNuspec(String name, String version, String nuspecFilename, FindPackageByIdResource resource) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/NugetV3Service.cs:line 324
07:26:30      at CycloneDX.Services.NugetV3Service.GetComponentAsync(String name, String version, Nullable`1 scope) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/NugetV3Service.cs:line 174
07:26:30      at CycloneDX.Services.NugetV3Service.GetComponentAsync(DotnetDependency DotnetDependency) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/NugetV3Service.cs:line 366
07:26:30      at CycloneDX.Runner.HandleCommandAsync(RunOptions options) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Runner.cs:line 258
07:26:30      at CycloneDX.Program.<>c__DisplayClass0_0.<<Main>b__2>d.MoveNext() in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 137
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
07:26:30      at System.CommandLine.Invocation.AnonymousCommandHandler.SyncUsingAsync(InvocationContext context)
07:26:30      at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
07:26:30   --- End of stack trace from previous location ---
07:26:30      at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by GeorgRottensteiner** [comment]
On further inspection this seems to be caused by internal packages which are fetched from an internal NuGet server. The projects with this issue use mixed packages from official nuget.org and an internal server.

CycloneDX seems to only support one package source?? Passing the internal source with -u makes it fail with the same message on official packages (which obviously don't exist on our internal server)
How can I make CycloneDX check with several package sources?

**Comment by trivalik** [comment]
This happens if the packet is not available on the configured (or default) NuGet Feed. The downloaded file size is 0.
