### ISSUE TITLE
Without arguments, ArgumentNullException

### ISSUE THREAD

**Issue by kwaazaar** [CycloneDX/cyclonedx-dotnet#7]
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at CycloneDX.Program.OnExecute() in /Users/steve/Development/CycloneDX/cyclonedx-dotnet/CycloneDX/Program.cs:line 51
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 97
   at CycloneDX.Program.Main(String[] args) in /Users/steve/Development/CycloneDX/cyclonedx-dotnet/CycloneDX/Program.cs:line 45

**Comment by stevespringett** [comment]
Thanks for the report. Do you have a way to replicate so that I can test the defect and the fix?

**Comment by coderpatros** [comment]
Did a bit of digging @stevespringett 

This affected version 0.3.3. Should be fine to close this issue now.

**Comment by stevespringett** [comment]
Thanks. Closing.
