### ISSUE TITLE
KeyNotFoundException with 2.8.0

### ISSUE THREAD

**Issue by Falco20019** [CycloneDX/cyclonedx-dotnet#725]
After updating to 2.8.0, I can not use CycloneDX anymore... This has not happened with 2.7.0.
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at CycloneDX.Services.ProjectAssetsFileService.SetIsDevDependency(String packageName, String targetRuntime, JsonElement jsonContent) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectAssetsFileService.cs:line 113
   at CycloneDX.Services.ProjectAssetsFileService.GetNugetPackages(String projectFilePath, String projectAssetsFilePath, Boolean isTestProject, Boolean excludeDev) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectAssetsFileService.cs:line 63
   at CycloneDX.Services.ProjectFileService.GetProjectNugetPackagesAsync(String projectFilePath, String baseIntermediateOutputPath, Boolean excludeTestProjects, Boolean excludeDev, String framework, String runtime) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectFileService.cs:line 145
   at CycloneDX.Program.OnExecuteAsync(CommandLineApplication app) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 255
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 140
   at CycloneDX.Program.<Main>(String[] args)
```

**Comment by Falco20019** [comment]
This happens if runtime identifiers are used. This will generate targets like:
* net6.0-windows10.0.19041
* net6.0-windows10.0.19041/win-x64
* net6.0-windows10.0.19041/win10-x64

But when looking up `project.frameworks` there will only be `net6.0-windows10.0.19041`. Trying to access the RID specific target will result in the exception.

**Comment by stand-sure** [comment]
seeing the same issue

version 2.7.0 does not have this problem

**Comment by NextFreeUsername** [comment]
Seeing the same symptom but in our case it is because of the lack of the "dependencies" element in the project.assets.json file beneath the project > frameworks. Resolving the framework from the target works in our case.

![image](https://github.com/CycloneDX/cyclonedx-dotnet/assets/15980711/c2851b0b-41a7-4b85-b77b-a7c6ef954b85)

**Comment by Falco20019** [comment]
I adjusted the PR to also cover those. Please be aware, that the `net48` should contain a `targetAlias` to be valid pointing to `.NETFramework,Version=v4.8` as used target.
