### ISSUE TITLE
Creation of SBOM fails when using central package management and CycloneDX 2.8.0

### ISSUE THREAD

**Issue by mrblumi** [CycloneDX/cyclonedx-dotnet#729]
Creating a SBOM fails with CycloneDX version 2.8.0 when using central package management via `Directory.Packages.props` while it was working perfectly fine with CycloneDX version 2.7.0

````
[2023-07-05T09:40:32.738Z] Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
[2023-07-05T09:40:32.738Z]    at CycloneDX.Services.ProjectAssetsFileService.GetNugetPackages(String projectFilePath, String projectAssetsFilePath, Boolean isTestProject, Boolean excludeDev) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectAssetsFileService.cs:line 46
[2023-07-05T09:40:32.738Z]    at CycloneDX.Services.ProjectFileService.GetProjectNugetPackagesAsync(String projectFilePath, String baseIntermediateOutputPath, Boolean excludeTestProjects, Boolean excludeDev, String framework, String runtime) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectFileService.cs:line 145
[2023-07-05T09:40:32.738Z]    at CycloneDX.Services.ProjectFileService.RecursivelyGetProjectNugetPackagesAsync(String projectFilePath, String baseIntermediateOutputPath, Boolean excludeTestProjects, Boolean excludeDev, String framework, String runtime) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Services/ProjectFileService.cs:line 174
[2023-07-05T09:40:32.739Z]    at CycloneDX.Program.OnExecuteAsync(CommandLineApplication app) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 250
[2023-07-05T09:40:32.739Z]    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
[2023-07-05T09:40:32.739Z]    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
[2023-07-05T09:40:32.739Z]    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
[2023-07-05T09:40:32.739Z] --- End of stack trace from previous location ---
[2023-07-05T09:40:32.739Z]    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
[2023-07-05T09:40:32.739Z]    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
[2023-07-05T09:40:32.739Z]    at CycloneDX.Program.Main(String[] args) in /home/runner/work/cyclonedx-dotnet/cyclonedx-dotnet/CycloneDX/Program.cs:line 140
[2023-07-05T09:40:32.739Z]    at CycloneDX.Program.<Main>(String[] args)
```

**Comment by sostrich** [comment]
had the same issue for 2.8.0, but upgrading to 2.8.1 fixed it.

**Comment by mrblumi** [comment]
There is already a 2.8.1? Nice, I will upgrade ASAP
